### ISSUE TITLE
http://unicode.org/cldr/utility/list-unicodeset.jsp?a=[%3AGC%3DZs%3A][%3ADI%3A]&abb=on&ucd=on&esc=on&g service unavilable

### ISSUE THREAD

**Issue by adancygier** [WritingMinds/ffmpeg-android#55]
When building Im getting the following error.  There is a dependency on a web service that appears to not be functional.  Is there an alternative you are aware of?

Making install in fc-blanks
make[1]: Entering directory `/home/aaron/git/ffmpeg-android/fontconfig/fc-blanks'
  GEN      fcblanks.h
Traceback (most recent call last):
  File "./fc-blanks.py", line 7, in <module>
    fp = urllib2.urlopen('http://unicode.org/cldr/utility/list-unicodeset.jsp?a=[%3AGC%3DZs%3A][%3ADI%3A]&abb=on&ucd=on&esc=on&g')
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Temporarily Unavailable
make[1]: *** [fcblanks.h] Error 1
make[1]: Leaving directory `/home/aaron/git/ffmpeg-android/fontconfig/fc-blanks'
make: *** [install-recursive] Error 1

**Comment by adancygier** [comment]
This is apparently parsing the DOM of a page response.  Is there a less brittle way to get this data.
