### ISSUE TITLE
Output file #0 does not contain any stream

### ISSUE THREAD

**Issue by lessismore100** [WritingMinds/ffmpeg-android#77]
ERROR:

Output file #0 does not contain any stream

[FFMPEG]

solution:<br></br>
so instead of passing an integrated string command you should do something like this:
String[] cmds = new String[12];
                cmds[0] = "-i";
                cmds[1] = "input_AYINGO500971992193.mp4";
                cmds[2] = "-y";
                cmds[3] = "-f";
                cmds[4] = "mjpeg";
                cmds[5] = "-ss";
                cmds[6] = "8";
                cmds[7] = "-t";
                cmds[8] = "0.001";
                cmds[9] = "-s";
                cmds[10] = "320x240";
                cmds[11] = "AYINGO_out.jpg";

**Comment by lessismore100** [comment]
This will prompt errors,like this: 
String[] cmd = {"ffmpeg -i " + "input_AYINGO500971992193.mp4" + " -y -f mjpeg -ss 8 -t 0.001 -s 320x240 AYINGO_out.jpg"}; //{"-version"};

**Comment by sathiz1314** [comment]
ERROR:

Output #0, mp4, to 'ffmpeg -loop 1 -t 3 -i /storage/emulated/0/Pictures/Screenshots/Screenshot_20170824-151931.png -loop 1 -t 3 -i /storage/emulated/0/Pictures/Screenshots/Screenshot_20170824-151920.png -loop 1 -t 3 -i /storage/emulated/0/Pictures/Screenshots/Screenshot_20170824-151714.png -loop 1 -t 3 -i /storage/emulated/0/Pictures/Screenshots/Screenshot_20170824-151738.png -filter_complex [0:v]trim=duration=3,fade=t=out:st=2.5:d=0.5[v0];[1:v]trim=duration=3,fade=t=in:st=0:d=0.5,fade=t=out:st=2.5:d=0.5[v1];[2:v]trim=duration=3,fade=t=in:st=0:d=0.5,fade=t=out:st=2.5:d=0.5[v2];[3:v]trim=duration=3,fade=t=in:st=0:d=0.5,fade=t=out:st=2.5:d=0.5[v3];[v0][v1][v2][v3]concat=n=4:v=1:a=0,format=yuv420p[v] -map [v] -preset ultrafast /storage/emulated/0/sample.mp4':

 Output file #0 does not contain any stream
fmpeg version n3.0.1 Copyright (c) 2000-2016 the FFmpeg developers
                                                                   built with gcc 4.8 (GCC)

configuration: --target-os=linux --cross-prefix=/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/bin/arm-linux-androideabi- --arch=arm --cpu=cortex-a8 --enable-runtime-cpudetect --sysroot=/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/sysroot --enable-pic --enable-libx264 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-fontconfig --enable-pthreads --disable-debug --disable-ffserver --enable-version3 --enable-hardcoded-tables --disable-ffplay --disable-ffprobe --enable-gpl --enable-yasm --disable-doc --disable-shared --enable-static --pkg-config=/home/vagrant/SourceCode/ffmpeg-android/ffmpeg-pkg-config --prefix=/home/vagrant/SourceCode/ffmpeg-android/build/armeabi-v7a --extra-cflags='-I/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all' --extra-ldflags='-L/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/lib -Wl,-z,relro -Wl,-z,now -pie' --extra-libs='-lpng -lexpat -lm' --extra-cxxflags=
                                                                   libavutil      55. 17.103 / 55. 17.103
                                                                   libavcodec     57. 24.102 / 57. 24.102
                                                                   libavformat    57. 25.100 / 57. 25.100
                                                                   libavdevice    57.  0.101 / 57.  0.101
                                                                   libavfilter     6. 31.100 /  6. 31.100
                                                                   libswscale      4.  0.100 /  4.  0.100
                                                                   libswresample   2.  0.101 /  2.  0.101
                                                                   libpostproc    54.  0.100 / 54.  0.100

 Output #0, mp4, to 'ffmpeg -loop 1 -t 3 -i /storage/emulated/0/Pictures/Screenshots/Screenshot_20170824-151931.png -loop 1 -t 3 -i /storage/emulated/0/Pictures/Screenshots/Screenshot_20170824-151920.png -loop 1 -t 3 -i /storage/emulated/0/Pictures/Screenshots/Screenshot_20170824-151714.png -loop 1 -t 3 -i /storage/emulated/0/Pictures/Screenshots/Screenshot_20170824-151738.png -filter_complex [0:v]trim=duration=3,fade=t=out:st=2.5:d=0.5[v0];[1:v]trim=duration=3,fade=t=in:st=0:d=0.5,fade=t=out:st=2.5:d=0.5[v1];[2:v]trim=duration=3,fade=t=in:st=0:d=0.5,fade=t=out:st=2.5:d=0.5[v2];[3:v]trim=duration=3,fade=t=in:st=0:d=0.5,fade=t=out:st=2.5:d=0.5[v3];[v0][v1][v2][v3]concat=n=4:v=1:a=0,format=yuv420p[v] -map [v] -preset ultrafast /storage/emulated/0/sample.mp4':

Output file #0 does not contain any stream

**Comment by saulwiggin** [comment]
Same problem!

**Comment by saulwiggin** [comment]
START RequestId: dce8934c-e44c-463c-a2ff-ebbb40f994b0 Version: $LATEST
2020-01-28T12:03:00.425Z	dce8934c-e44c-463c-a2ff-ebbb40f994b0	INFO	converting saul.wiggin.lambda.ffmpeg somesuch_229_loop.mp4 using /tmp/dce8934c-e44c-463c-a2ff-ebbb40f994b0.mp4
2020-01-28T12:03:00.426Z	dce8934c-e44c-463c-a2ff-ebbb40f994b0	INFO	downloading saul.wiggin.lambda.ffmpeg somesuch_229_loop.mp4 /tmp/dce8934c-e44c-463c-a2ff-ebbb40f994b0.mp4
2020-01-28T12:03:00.611Z	dce8934c-e44c-463c-a2ff-ebbb40f994b0	INFO	downloaded saul.wiggin.lambda.ffmpeg somesuch_229_loop.mp4
2020-01-28T12:03:00.611Z	dce8934c-e44c-463c-a2ff-ebbb40f994b0	INFO	executing /opt/bin/ffmpeg  -i /tmp/dce8934c-e44c-463c-a2ff-ebbb40f994b0.mp4 -vf boxblur=5:1 /tmp/dce8934c-e44c-463c-a2ff-ebbb40f994b0.mp4
2020-01-28T12:03:00.705Z	dce8934c-e44c-463c-a2ff-ebbb40f994b0	ERROR	ffmpeg version 4.1.3-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzvbi --enable-libzimg
2020-01-28T12:03:00.714Z	dce8934c-e44c-463c-a2ff-ebbb40f994b0	ERROR	  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
2020-01-28T12:03:00.744Z	dce8934c-e44c-463c-a2ff-ebbb40f994b0	ERROR	Output #0, mp4, to ' -i /tmp/dce8934c-e44c-463c-a2ff-ebbb40f994b0.mp4 -vf boxblur=5:1 /tmp/dce8934c-e44c-463c-a2ff-ebbb40f994b0.mp4':
Output file #0 does not contain any stream
2020-01-28T12:03:00.754Z	dce8934c-e44c-463c-a2ff-ebbb40f994b0	INFO	/opt/bin/ffmpeg completed with 1:null
2020-01-28T12:03:00.754Z	dce8934c-e44c-463c-a2ff-ebbb40f994b0	ERROR	Invoke Error	{"errorType":"Error","errorMessage":"/opt/bin/ffmpeg failed with 1","stack":["Error: /opt/bin/ffmpeg failed with 1","    at _homogeneousError (/var/runtime/CallbackContext.js:13:12)","    at postError (/var/runtime/CallbackContext.js:30:51)","    at done (/var/runtime/CallbackContext.js:57:7)","    at fail (/var/runtime/CallbackContext.js:69:7)","    at /var/runtime/CallbackContext.js:105:16","    at process._tickCallback (internal/process/next_tick.js:68:7)"]}
END RequestId: dce8934c-e44c-463c-a2ff-ebbb40f994b0
REPORT RequestId: dce8934c-e44c-463c-a2ff-ebbb40f994b0	Duration: 333.79 ms	Billed Duration: 400 ms	Memory Size: 3008 MB	Max Memory Used: 133 MB	Init Duration: 363.82 ms
